services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v3pf
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./public:/app/public
      - ./content:/app/content

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - nuxt-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
