services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v3pf
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik-network

networks:
  traefik-network:
