version: "3.8"

services:
  nuxt-app:
    build: . # Build the Dockerfile in the current directory
    container_name: v3pf
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    env_file:
      - .env # Load environment variables from .env
    restart: unless-stopped # Automatically restart the container if it stops
