services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v3pf
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik-network
    volumes:
      - ./public:/app/public
      - ./content:/app/content

networks:
  traefik-network:

volumes:
  public_volume:
  content_volume:
