name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Copy files to VM and deploy
      - name: Test tar command
        run: |
          echo "Testing tar command..."
          tar -czf - . | ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "tar -xzf - -C /var/www/portfolio && echo 'Files copied successfully' || echo 'Failed to copy files'"

      - name: Verify files on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            ls -la /var/www/portfolio
