name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    run-on: ubuntu-latest

    steps:
      - name: Checkout code
        use: actions/checkout@v3

      - name: Test SSH Connection
        use: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: echo "SSH Connection successful"
